# Generated by Django 6.0 on 2026-02-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpvDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpv_parent_code', models.CharField(max_length=50)),
                ('cpv_level_code', models.CharField(max_length=50)),
                ('cpv_code', models.CharField(max_length=50)),
                ('name_ua', models.TextField(blank=True, default='')),
                ('name_en', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'cpv_dictionary',
                'ordering': ['cpv_code'],
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='cpvs',
            field=models.ManyToManyField(blank=True, help_text="CPV-коди, прив'язані до категорії", related_name='categories', to='core.cpvdictionary'),
        ),
    ]
