# Generated by Django 6.0 on 2026-02-11 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_category_cpvs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('year_start', models.PositiveIntegerField()),
                ('year_end', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_articles', to='core.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.expensearticle')),
            ],
            options={
                'verbose_name': 'Стаття витрат',
                'verbose_name_plural': 'Статті витрат',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseArticleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.expensearticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Користувач статті витрат',
                'verbose_name_plural': 'Користувачі статей витрат',
                'unique_together': {('expense', 'user')},
            },
        ),
    ]
