# Generated by Django 6.0 on 2026-02-12 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_expense_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units_of_measure', to='core.company')),
            ],
            options={
                'verbose_name': 'Одиниця виміру',
                'verbose_name_plural': 'Одиниці виміру',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default='', help_text='Код / артикул', max_length=100)),
                ('external_number', models.CharField(blank=True, default='', help_text='Зовнішній номер', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('specification_file', models.CharField(blank=True, default='', help_text='Шлях або ідентифікатор файлу специфікації (MVP: як текстове поле)', max_length=255)),
                ('image_file', models.CharField(blank=True, default='', help_text='Шлях або ідентифікатор зображення (MVP: як текстове поле)', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Звичайна категорія довідника', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomenclatures', to='core.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomenclatures', to='core.company')),
                ('cpv_category', models.ForeignKey(blank=True, help_text='CPV-категорія, якщо не використовується звичайна категорія', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomenclatures', to='core.cpvdictionary')),
                ('unit', models.ForeignKey(help_text='Одиниця виміру', on_delete=django.db.models.deletion.PROTECT, related_name='nomenclatures', to='core.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
                'ordering': ['name'],
            },
        ),
    ]
