# Generated by Django 6.0 on 2026-02-13 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_unitofmeasure_nomenclature'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('numeric', 'Числовий'), ('text', 'Текстовий'), ('file', 'Файловий'), ('boolean', 'Булевий (Так/Ні)')], max_length=20)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_criteria', to='core.company')),
            ],
            options={
                'verbose_name': 'Критерій тендеру',
                'verbose_name_plural': 'Критерії тендерів',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
