# Generated by Django 6.0 on 2026-02-13 22:18

import django.db.models.deletion
from django.db import migrations, models


def copy_cpv_category_to_cpv_categories(apps, schema_editor):
    Nomenclature = apps.get_model("core", "Nomenclature")
    ProcurementTender = apps.get_model("core", "ProcurementTender")
    SalesTender = apps.get_model("core", "SalesTender")
    for obj in Nomenclature.objects.filter(cpv_category_id__isnull=False):
        obj.cpv_categories.add(obj.cpv_category_id)
    for obj in ProcurementTender.objects.filter(cpv_category_id__isnull=False):
        obj.cpv_categories.add(obj.cpv_category_id)
    for obj in SalesTender.objects.filter(cpv_category_id__isnull=False):
        obj.cpv_categories.add(obj.cpv_category_id)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_sales_tender'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='cpv_categories',
            field=models.ManyToManyField(blank=True, help_text="CPV-категорії для прив'язки номенклатури", related_name='nomenclatures_by_cpvs', to='core.cpvdictionary'),
        ),
        migrations.AddField(
            model_name='procurementtender',
            name='cpv_categories',
            field=models.ManyToManyField(blank=True, help_text='CPV-категорії тендера', related_name='procurement_tenders_by_cpvs', to='core.cpvdictionary'),
        ),
        migrations.AddField(
            model_name='salestender',
            name='cpv_categories',
            field=models.ManyToManyField(blank=True, help_text='CPV-категорії тендера', related_name='sales_tenders_by_cpvs', to='core.cpvdictionary'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='cpv_category',
            field=models.ForeignKey(blank=True, help_text='CPV-категорія (зберігається для сумісності, використовуйте cpv_categories)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomenclatures', to='core.cpvdictionary'),
        ),
        migrations.AlterField(
            model_name='procurementtender',
            name='cpv_category',
            field=models.ForeignKey(blank=True, help_text='Зберігається для сумісності, використовуйте cpv_categories', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_tenders', to='core.cpvdictionary'),
        ),
        migrations.AlterField(
            model_name='salestender',
            name='cpv_category',
            field=models.ForeignKey(blank=True, help_text='Зберігається для сумісності, використовуйте cpv_categories', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_tenders', to='core.cpvdictionary'),
        ),
        migrations.RunPython(copy_cpv_category_to_cpv_categories, noop),
    ]
