# Generated by Django 6.0 on 2026-02-14 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_companysupplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysupplier',
            options={'ordering': ['-created_at'], 'verbose_name': 'Контрагент компанії', 'verbose_name_plural': 'Контрагенти компанії'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='companysupplier',
            name='owner_company',
            field=models.ForeignKey(help_text='Компанія, для якої ведеться список контрагентів', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_relations', to='core.company'),
        ),
        migrations.AlterField(
            model_name='companysupplier',
            name='supplier_company',
            field=models.ForeignKey(help_text='Компанія-контрагент', on_delete=django.db.models.deletion.CASCADE, related_name='as_supplier_for', to='core.company'),
        ),
    ]
