# Generated by Django 6.0 on 2026-02-14 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_avatar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unitofmeasure',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units_of_measure', to='core.company'),
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('name',), name='core_unitofmeasure_shared_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'name'), name='core_unitofmeasure_company_name_unique'),
        ),
    ]
