# Generated by Django 6.0 on 2026-02-15 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_unitofmeasure_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementtender',
            name='price_criterion_delivery',
            field=models.CharField(blank=True, default='', help_text='Наприклад: with_delivery, without_delivery', max_length=32),
        ),
        migrations.AddField(
            model_name='procurementtender',
            name='price_criterion_vat',
            field=models.CharField(blank=True, default='', help_text='Наприклад: with_vat, without_vat', max_length=32),
        ),
        migrations.AddField(
            model_name='procurementtender',
            name='tender_criteria',
            field=models.ManyToManyField(blank=True, help_text='Критерії тендера (крім ціни)', related_name='procurement_tenders', to='core.tendercriterion'),
        ),
        migrations.CreateModel(
            name='ProcurementTenderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tender_files/%Y/%m/')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='core.procurementtender')),
            ],
            options={
                'verbose_name': 'Файл тендера',
                'verbose_name_plural': 'Файли тендера',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementTenderPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ('description', models.TextField(blank=True, default='')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_tender_positions', to='core.nomenclature')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.procurementtender')),
            ],
            options={
                'verbose_name': 'Позиція тендера на закупівлю',
                'verbose_name_plural': 'Позиції тендера на закупівлю',
                'ordering': ['id'],
                'unique_together': {('tender', 'nomenclature')},
            },
        ),
        migrations.CreateModel(
            name='TenderProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_proposals_as_supplier', to='core.company')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='core.procurementtender')),
            ],
            options={
                'verbose_name': 'Пропозиція в тендері',
                'verbose_name_plural': 'Пропозиції в тендері',
                'ordering': ['id'],
                'unique_together': {('tender', 'supplier_company')},
            },
        ),
        migrations.CreateModel(
            name='TenderProposalPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('criterion_values', models.JSONField(blank=True, default=dict)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_values', to='core.tenderproposal')),
                ('tender_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_values', to='core.procurementtenderposition')),
            ],
            options={
                'verbose_name': 'Позиція пропозиції',
                'verbose_name_plural': 'Позиції пропозицій',
                'ordering': ['tender_position_id'],
                'unique_together': {('proposal', 'tender_position')},
            },
        ),
    ]
