# Generated by Django 6.0 on 2026-02-15 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_sales_tender_positions_proposals_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementtenderposition',
            name='winner_proposal',
            field=models.ForeignKey(blank=True, help_text='Переможець по цій позиції (після фіксації рішення)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_positions', to='core.tenderproposal'),
        ),
        migrations.AddField(
            model_name='salestenderposition',
            name='winner_proposal',
            field=models.ForeignKey(blank=True, help_text='Переможець по цій позиції (після фіксації рішення)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_positions', to='core.salestenderproposal'),
        ),
    ]
