# Generated by Django 6.0 on 2026-02-16 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_position_winner_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementtenderposition',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Назва позиції (знімок з номенклатури на момент додавання)', max_length=500),
        ),
        migrations.AddField(
            model_name='procurementtenderposition',
            name='unit_name',
            field=models.CharField(blank=True, default='', help_text='Одиниця виміру (знімок)', max_length=100),
        ),
        migrations.AddField(
            model_name='salestenderposition',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Назва позиції (знімок з номенклатури на момент додавання)', max_length=500),
        ),
        migrations.AddField(
            model_name='salestenderposition',
            name='unit_name',
            field=models.CharField(blank=True, default='', help_text='Одиниця виміру (знімок)', max_length=100),
        ),
        migrations.AlterField(
            model_name='procurementtender',
            name='tender_criteria',
            field=models.ManyToManyField(blank=True, help_text='Критерії тендера (крім ціни); зберігається для міграції, використовуйте criteria_snapshots', related_name='procurement_tenders', to='core.tendercriterion'),
        ),
        migrations.AlterField(
            model_name='procurementtenderposition',
            name='nomenclature',
            field=models.ForeignKey(help_text="Зв'язок з довідником; відображення в тендері йде з name/unit_name", on_delete=django.db.models.deletion.PROTECT, related_name='procurement_tender_positions', to='core.nomenclature'),
        ),
        migrations.AlterField(
            model_name='salestender',
            name='tender_criteria',
            field=models.ManyToManyField(blank=True, help_text='Критерії тендера (крім ціни); зберігається для міграції, використовуйте criteria_snapshots', related_name='sales_tenders', to='core.tendercriterion'),
        ),
        migrations.CreateModel(
            name='ProcurementTenderCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('numeric', 'Числовий'), ('text', 'Текстовий'), ('file', 'Файловий'), ('boolean', 'Булевий (Так/Ні)')], max_length=20)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('reference_criterion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_tender_snapshots', to='core.tendercriterion')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_snapshots', to='core.procurementtender')),
            ],
            options={
                'verbose_name': 'Критерій тендера на закупівлю (знімок)',
                'verbose_name_plural': 'Критерії тендера на закупівлю (знімки)',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalesTenderCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('numeric', 'Числовий'), ('text', 'Текстовий'), ('file', 'Файловий'), ('boolean', 'Булевий (Так/Ні)')], max_length=20)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('reference_criterion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_tender_snapshots', to='core.tendercriterion')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_snapshots', to='core.salestender')),
            ],
            options={
                'verbose_name': 'Критерій тендера на продаж (знімок)',
                'verbose_name_plural': 'Критерії тендера на продаж (знімки)',
                'ordering': ['id'],
            },
        ),
    ]
