# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_add_position_snapshot_fields_and_criterion_snapshots"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="unitofmeasure",
            name="core_unitofmeasure_shared_name_unique",
        ),
        migrations.RemoveConstraint(
            model_name="unitofmeasure",
            name="core_unitofmeasure_company_name_unique",
        ),
        migrations.RenameField(
            model_name="unitofmeasure",
            old_name="name",
            new_name="name_ua",
        ),
        migrations.AddField(
            model_name="unitofmeasure",
            name="name_en",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddConstraint(
            model_name="unitofmeasure",
            constraint=models.UniqueConstraint(
                condition=models.Q(("company__isnull", True)),
                fields=("name_ua",),
                name="core_unitofmeasure_shared_name_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="unitofmeasure",
            constraint=models.UniqueConstraint(
                condition=models.Q(("company__isnull", False)),
                fields=("company", "name_ua"),
                name="core_unitofmeasure_company_name_unique",
            ),
        ),
    ]
