# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_unitofmeasure_name_ua_name_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitofmeasure",
            name="short_name_ua",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="unitofmeasure",
            name="short_name_en",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
