# Generated by Django 6.0 on 2026-02-18 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_company_cpv_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salestendercriterion',
            name='reference_criterion',
        ),
        migrations.RemoveField(
            model_name='salestendercriterion',
            name='tender',
        ),
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={'ordering': ['name_ua'], 'verbose_name': 'Одиниця виміру', 'verbose_name_plural': 'Одиниці виміру'},
        ),
        migrations.AlterField(
            model_name='procurementtender',
            name='tender_criteria',
            field=models.ManyToManyField(blank=True, help_text='Критерії тендера (крім ціни)', related_name='procurement_tenders', to='core.tendercriterion'),
        ),
        migrations.AlterField(
            model_name='salestender',
            name='tender_criteria',
            field=models.ManyToManyField(blank=True, help_text='Критерії тендера (крім ціни)', related_name='sales_tenders', to='core.tendercriterion'),
        ),
        migrations.DeleteModel(
            name='ProcurementTenderCriterion',
        ),
        migrations.DeleteModel(
            name='SalesTenderCriterion',
        ),
    ]
