# Generated by Django 6.0 on 2026-02-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_tender_file_uploaded_by_visible'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tendercriterion',
            unique_together={('company', 'name', 'type')},
        ),
        migrations.AddField(
            model_name='tendercriterion',
            name='application',
            field=models.CharField(choices=[('general', 'Загальний'), ('individual', 'Індивідуальний')], default='individual', help_text='Загальний — одне значення на тендер; індивідуальний — по кожній позиції.', max_length=20),
        ),
    ]
