# Generated by Django 6.0 on 2026-02-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_criterion_application_and_unique_name_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestenderproposal',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='Час подачі пропозиції; null — не подано або відкликано', null=True),
        ),
        migrations.AddField(
            model_name='tenderproposal',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='Час подачі пропозиції; null — не подано або відкликано', null=True),
        ),
    ]
