# Generated by Django 6.0 on 2026-03-06 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_proposal_delta_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderapprovaljournal',
            name='action',
            field=models.CharField(choices=[('saved', 'Збережено'), ('published', 'Опубліковано'), ('approved', 'Погоджено'), ('rejected', 'Скасовано')], max_length=20),
        ),
        migrations.CreateModel(
            name='TenderApprovalStageState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('preparation', 'Підготовка процедури'), ('approval', 'Затвердження')], max_length=20)),
                ('status', models.CharField(choices=[('waiting_author', 'Очікує дії автора'), ('in_progress', 'В процесі погодження'), ('approved', 'Погоджено'), ('rejected', 'Відхилено')], default='waiting_author', max_length=20)),
                ('current_order', models.PositiveIntegerField(blank=True, null=True)),
                ('cycle', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procurement_tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_stage_states', to='core.procurementtender')),
                ('sales_tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_stage_states', to='core.salestender')),
            ],
            options={
                'verbose_name': 'Стан погодження етапу тендера',
                'verbose_name_plural': 'Стани погодження етапів тендерів',
                'ordering': ['-updated_at', '-id'],
                'unique_together': {('procurement_tender', 'stage'), ('sales_tender', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='TenderApprovalStageStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('role_name', models.CharField(blank=True, default='', max_length=255)),
                ('approval_rule', models.CharField(choices=[('one_of', 'Один зі'), ('all', 'Усі')], default='one_of', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.approvalmodelrole')),
                ('stage_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.tenderapprovalstagestate')),
            ],
            options={
                'verbose_name': 'Крок погодження етапу тендера',
                'verbose_name_plural': 'Кроки погодження етапів тендерів',
                'ordering': ['order', 'id'],
                'unique_together': {('stage_state', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TenderApprovalStageStepUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('active', 'Активне завдання'), ('approved', 'Погоджено'), ('skipped', 'Пропущено'), ('rejected', 'Відхилено')], default='pending', max_length=20)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_users', to='core.tenderapprovalstagestep')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Користувач кроку погодження',
                'verbose_name_plural': 'Користувачі кроків погодження',
                'ordering': ['id'],
                'unique_together': {('step', 'user')},
            },
        ),
    ]
