# Generated by Django 6.0.1 on 2026-03-07 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_tenderapprovaljournal_action_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensearticle',
            options={'ordering': ['name'], 'verbose_name': 'Стаття бюджету', 'verbose_name_plural': 'Статті бюджету'},
        ),
        migrations.AlterModelOptions(
            name='expensearticleuser',
            options={'verbose_name': 'Користувач статті бюджету', 'verbose_name_plural': 'Користувачі статей бюджету'},
        ),
    ]
