# Generated by Django 6.0 on 2026-03-14 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_tender_condition_template_and_auction_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestenderproposal',
            name='disqualification_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salestenderproposal',
            name='disqualified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salestenderproposal',
            name='disqualified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disqualified_sales_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenderproposal',
            name='disqualification_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenderproposal',
            name='disqualified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenderproposal',
            name='disqualified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disqualified_procurement_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('membership_request', 'Запит на приєднання'), ('chat_message', 'Повідомлення у чаті тендера'), ('tender_to_decision', 'Тендер перейшов на вибір рішення'), ('tender_completed', 'Тендер завершено')], max_length=64),
        ),
        migrations.CreateModel(
            name='TenderChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_type', models.CharField(choices=[('procurement', 'Закупівля'), ('sales', 'Продаж')], max_length=16)),
                ('tender_id', models.PositiveIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('supplier_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_chat_threads', to='core.company')),
            ],
            options={
                'verbose_name': 'Чат тендера',
                'verbose_name_plural': 'Чати тендерів',
                'ordering': ['-last_message_at', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TenderChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tender_chat_messages', to='core.company')),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tender_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.tenderchatthread')),
            ],
            options={
                'verbose_name': 'Повідомлення чату тендера',
                'verbose_name_plural': 'Повідомлення чатів тендерів',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TenderProposalChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_type', models.CharField(choices=[('procurement', 'Закупівля'), ('sales', 'Продаж')], max_length=16)),
                ('tender_id', models.PositiveIntegerField(db_index=True)),
                ('proposal_id', models.PositiveIntegerField(db_index=True)),
                ('tender_position_id', models.PositiveIntegerField(db_index=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('original_criterion_values', models.JSONField(blank=True, default=dict)),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('current_criterion_values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_proposal_change_logs', to='core.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tender_proposal_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Звіт змін КП',
                'verbose_name_plural': 'Звіти змін КП',
                'ordering': ['supplier_company__name', 'tender_position_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TenderBidHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_type', models.CharField(choices=[('procurement', 'Закупівля'), ('sales', 'Продаж')], max_length=16)),
                ('tender_id', models.PositiveIntegerField(db_index=True)),
                ('proposal_id', models.PositiveIntegerField(db_index=True)),
                ('tender_position_id', models.PositiveIntegerField(db_index=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tender_bid_history_entries', to=settings.AUTH_USER_MODEL)),
                ('supplier_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_bid_history', to='core.company')),
            ],
            options={
                'verbose_name': 'Історія ставки тендера',
                'verbose_name_plural': 'Історія ставок тендерів',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tender_type', 'tender_id', 'tender_position_id', 'created_at'], name='tbid_tender_pos_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tenderchatthread',
            index=models.Index(fields=['tender_type', 'tender_id', 'last_message_at'], name='tchat_tender_last_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenderchatthread',
            unique_together={('tender_type', 'tender_id', 'supplier_company')},
        ),
        migrations.AddIndex(
            model_name='tenderchatmessage',
            index=models.Index(fields=['thread', 'created_at'], name='tchat_msg_thread_idx'),
        ),
        migrations.AddIndex(
            model_name='tenderproposalchangelog',
            index=models.Index(fields=['tender_type', 'tender_id', 'updated_at'], name='tchg_tender_updated_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenderproposalchangelog',
            unique_together={('tender_type', 'proposal_id', 'tender_position_id')},
        ),
    ]
